Use SHALL_DIR

diff --git a/bin/shall b/bin/shall
--- a/bin/shall
+++ b/bin/shall
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-shall_dir=$(dirname $(dirname $(readlink $(which shall))))
-shall_logs_dir="$shall_dir/logs/"
-
 if [ -z "$2" ]
 then
     echo "Usage: shall <GROUP> <COMMAND> [ARGS]"
@@ -10,6 +7,14 @@ then
 fi
 
 group=$1
+
+if [ -z "$SHALL_DIR" ]
+then
+    echo "Error: SHALL_DIR is not defined."
+    exit 1
+fi
+
+shall_logs_dir="$SHALL_DIR/logs/"
 
 set -e
 shalld "${@:1}"
diff --git a/bin/shall-script b/bin/shall-script
--- a/bin/shall-script
+++ b/bin/shall-script
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-shall_dir=$(dirname $(dirname $(readlink $(which shall))))
-shall_logs_dir="$shall_dir/logs/"
-
 if [ -z "$2" ]
 then
     echo "Usage: shallscript <GROUP> <URL>"
@@ -11,6 +8,14 @@ fi
 
 group=$1
 url=$2
+
+if [ -z "$SHALL_DIR" ]
+then
+    echo "Error: SHALL_DIR is not defined."
+    exit 1
+fi
+
+shall_logs_dir="$SHALL_DIR/logs/"
 
 http_status_code=$(curl -s -o /dev/null -w %{http_code} $url)
 
diff --git a/bin/shalld b/bin/shalld
--- a/bin/shalld
+++ b/bin/shalld
@@ -1,9 +1,5 @@
 #!/bin/bash
 
-shall_dir=$(dirname $(dirname $(readlink $(which shall))))
-shall_groups_dir="$shall_dir/groups/"
-shall_logs_dir="$shall_dir/logs/"
-
 if [ -z "$2" ]
 then
     echo "Usage: shalld <GROUP> <COMMAND> [ARGS]"
@@ -12,9 +8,18 @@ fi
 
 group=$1
 
+if [ -z "$SHALL_DIR" ]
+then
+    echo "Error: SHALL_DIR is not defined."
+    exit 1
+fi
+
+shall_groups_dir="$SHALL_DIR/groups/"
+shall_logs_dir="$SHALL_DIR/logs/"
+
 if [ ! -e $shall_groups_dir/$group ]
 then
-    echo "Unable to find group $group."
+    echo "Error: Unable to find group $group."
     exit 1
 fi
 
@@ -24,5 +29,5 @@ mkdir -p $shall_logs_dir/$group
 cd $shall_logs_dir/$group
 
 for host in $hosts; do
-    ssh -o StrictHostKeyChecking=accept-new $host "${@:2}" >> $host 2>&1 &
+    ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes -T $host "${@:2}" >> $host 2>&1 &
 done
